---
title: "<center><div class='mytitle'>Get Involved</div></center>"
subtitle: "<center><div class='mysubtitle'>_Join the movement for better education</div></center>"
output: 
  html_document:
    css: style.css
    includes: 
        before_body: header.html
---


<div class="mycontent">



## Learning about FORRT
***
We recently released a preprint introducing FORRT. [https://osf.io/bnh7p](https://osf.io/bnh7p)


## Getting Involved
***

We have also opened a Slack channel to keep everyone up-to-date and to provide a platform for ongoing discussions. You can join the channel here [https://tinyurl.com/FORRTslack](https://tinyurl.com/FORRTslack). 


<br>

We created a live-version of the manuscript for community participation and feedback [tinyURL.com/FORRTworkingDOC](tinyURL.com/FORRTworkingDOC). FORRT is operated as an open contributorship - all are welcome to contribute, and we aim to recognise all contributions. See the [manuscript](https://tinyurl.com/FORRTslack) for more information.

<br>

<br><br>

```{redcars}
[be more specific here. we need help with several parts of educational hub and pedagogies]
```

<br>

We are asking contributions for FORRT educational NEXUS, an e-learning platform acting as a hub for community-driven initiatives and resources. In this sense, the manuscript is only a (small) part of FORRT. As described in the manuscript, this platform will present the fullest opportunity FORRT has to offer. We will be particularly interested in contributions to the website, so if you (or your peers) are able to contribute to the development of the website, you would be helping make FORRT a powerful reality. But we also welcome other essential contributions such sharing your course materials, volunteering for OS mentoring, and submitting pedagogical reports of open and reproducible courses. 

<br>

</div>
