---
title: "<center><div class='mytitle'>Mission</div></center>"
subtitle: "<center><div class='mysubtitle'>_Goals & Aims_</div></center>"
output: 
  html_document:
    css: style.css
    includes: 
        before_body: header.html
---


<div class="mycontent">

## Our goals are straightforward:
***



* We hope FORRT will kickstart start a conversation on, and advocate for, placing greater support and value in teaching and mentoring – including raising the profile of open teaching materials and recognising their value.
* We hope FORRT ...
* We hope FORRT will be a useful tool supporting teachers looking to integrate open and reproducible research practices in their courses. For this we provide a pedagogy for incremental implementation of  


To achieve our goals, and in line with principles enshrined in FORRT, its manuscript will become an open online contributorship project, wherein the work of those supporting OS pedagogies are valued and formally recognized. The same can be said about any contribution to the construction, improvement and maintenance of FORRT's website. With this, we hope to expand the scope and diversity of FORRT’s mission and its team. [Join us in this mission](https://forrtv2.netlify.com/getinvolved).



</div>
